### ISSUE TITLE
Production QA 

### ISSUE THREAD

**Issue by giratikanon** [medillcherubs/2015-wordpress-site#20]
- [x] Create categories
- [x] Put a normal story on each subcategory
- [ ] Put a featured story in each subcategory
- [ ] Put a story on each homepage teaser slot
- [ ] Embed one of each media
- [ ] Test bylines and also by on full-width template
- [ ] Test bylines and also by on normal template

**Comment by sisiwei** [comment]
Each media:
- [x] Audio
- [ ] Video
- [x] Photo
- [x] Photo Slideshow

**Comment by giratikanon** [comment]
Done for practical purposes.
