### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by giratikanon** [medillcherubs/2015-wordpress-site#5]
Create an easy way to add Vimeo videos to the site.

**Comment by sisiwei** [comment]
Embedded `<iframe>` tags. Example:

```
<iframe src="//player.vimeo.com/video/103139311?byline=0&amp;portrait=0" width="565" height="318" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
```

**Comment by giratikanon** [comment]
All Vimeo players should resize to 16:9 on window resize: https://github.com/medillcherubs/2015-wordpress-site/blob/b3ed1b1d033cc307151732e10a23e65301d085a0/wp-content/themes/cherubs-2015/script.js#L4-L32
